apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: codelabs-ingress
    namespace: codelabs-ns
  spec:
    ingressClassName: nginx
    rules:
    - host: codelabs.appr.drw
      http:
        paths:
        - backend:
            serviceName: codelabs-wl
            servicePort: 8000
          path: /
          pathType: ImplementationSpecific
    tls:
    - hosts:
      - codelabs.appr.drw
      secretName: appr-dot-drw-wildcard-cert
kind: List
metadata:
  resourceVersion: ""
